export const getSessions = async () => {
  return [
    {
      id: 1,
      title: 'Internship Orientation',
      cohort: 'Cohort 3',
      programmeType: 'Law Student Internship',
      facilitator: 'Adebayo Lawal',
      date: '2026-04-20',
      time: '10:00 AM',
      duration: 90,
      sessionType: 'Internship Session',
      status: 'scheduled',
      replayStatus: 'pending',
      replayUrl: '',
      zoomMeetingId: '9845632101',
    },
    {
      id: 2,
      title: 'Young Lawyer Strategy Class',
      cohort: 'Cohort 2',
      programmeType: 'Young Lawyer Coaching',
      facilitator: 'Amaka Udeh',
      date: '2026-04-18',
      time: '2:00 PM',
      duration: 60,
      sessionType: 'Coaching',
      status: 'live',
      replayStatus: 'pending',
      replayUrl: '',
      zoomMeetingId: '9845632102',
    },
    {
      id: 3,
      title: 'Career Acceleration Q&A',
      cohort: 'Cohort 1',
      programmeType: 'Young Lawyer Coaching',
      facilitator: 'Tunde Balogun',
      date: '2026-04-10',
      time: '11:00 AM',
      duration: 75,
      sessionType: 'Q&A',
      status: 'completed',
      replayStatus: 'available',
      replayUrl: '',
      zoomMeetingId: '9845632103',
    },
  ]
}