// import api from '@/services/api'

// export const getUsers = async () => {
//   const { data } = await api.get('/admin/users')
//   return data
// }

export const getUsers = async () => {
  return [
    {
      id: 1,
      name: 'Samuel Owadokun',
      email: 'samuel@example.com',
      role: 'student',
      programme: 'Law Student Internship',
      cohort: 'Cohort 3',
      paymentStatus: 'fully paid',
      enrolmentStatus: 'active',
      dateRegistered: '2026-04-01',
      instalment1Amount: '₦50,000',
      instalment1Date: '2026-04-01',
      instalment2Amount: '₦50,000',
      instalment2Date: '2026-04-20',
      totalPaid: '₦100,000',
      outstandingBalance: '₦0',
      sessionsAttended: 8,
      totalSessions: 10,
      certificateStatus: 'eligible',
      referredBy: '—',
      referralsMade: 2,
      accessDisabledReason: '',
      accessDisabledNote: '',
    },
    {
      id: 2,
      name: 'Amaka Obi',
      email: 'amaka@example.com',
      role: 'young lawyer',
      programme: 'Young Lawyer Coaching',
      cohort: 'Cohort 2',
      paymentStatus: 'partial',
      enrolmentStatus: 'disabled',
      dateRegistered: '2026-03-25',
      instalment1Amount: '₦40,000',
      instalment1Date: '2026-03-25',
      instalment2Amount: '—',
      instalment2Date: '—',
      totalPaid: '₦40,000',
      outstandingBalance: '₦60,000',
      sessionsAttended: 3,
      totalSessions: 8,
      certificateStatus: 'in progress',
      referredBy: 'Samuel Owadokun',
      referralsMade: 0,
      accessDisabledReason: '',
      accessDisabledNote: '',
    },
    {
      id: 3,
      name: 'David Musa',
      email: 'david@example.com',
      role: 'student',
      programme: 'Law Student Internship',
      cohort: 'Cohort 1',
      paymentStatus: 'unpaid',
      enrolmentStatus: 'completed',
      dateRegistered: '2026-02-11',
      instalment1Amount: '—',
      instalment1Date: '—',
      instalment2Amount: '—',
      instalment2Date: '—',
      totalPaid: '₦0',
      outstandingBalance: '₦100,000',
      sessionsAttended: 7,
      totalSessions: 7,
      certificateStatus: 'not started',
      referredBy: '—',
      referralsMade: 1,
      accessDisabledReason: '',
      accessDisabledNote: '',
    },
    {
      id: 4,
      name: 'James Otti',
      email: 'james@example.com',
      role: 'young lawyer',
      programme: 'Young Lawyer Coaching',
      cohort: 'Cohort 2',
      paymentStatus: 'fully paid',
      enrolmentStatus: 'completed',
      dateRegistered: '2026-12-18',
      instalment1Amount: '₦50,000',
      instalment1Date: '2026-05-01',
      instalment2Amount: '₦50,000',
      instalment2Date: '2026-05-20',
      totalPaid: '₦100,000',
      outstandingBalance: '0',
      sessionsAttended: 8,
      totalSessions: 10,
      certificateStatus: 'eligible',
      referredBy: '—',
      referralsMade: 1,
      accessDisabledReason: '',
      accessDisabledNote: '',
    },
  ]
}